### ISSUE TITLE
Support for Ubuntu 23.04?

### ISSUE THREAD

**Issue by res1st** [telekom-mms/sectpmctl#34]
We have problems with die Lenovo DockingStation on 22.04 and they seems to be solved in 23.04 because of the new kernal.
Do you plan to support 23.04 soon?
That would help us a lot.

Best regards from Germany/Karlsruhe.
Ingo

**Comment by reitzrobert77** [comment]
Hello!

Sorry for the late response. Code to support Ubuntu >22.10 is currently in branch ubuntu_22_10_support. It will work, when sectpmctl is re-installed. What is still lacking is a sane upgrade path from 22.04 to >22.10 as PCR allocations did change starting from Ubuntu 22.10.

When Ubuntu version upgrades are not done (now or later) then it is perfectly safe to use ubuntu_22_10_support, otherwise it would be better to wait until upgrades are supported as it requires to remember which PCR allocation had initially been used.
